# Generated by Django 4.0.6 on 2022-07-25 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dname', models.CharField(max_length=50)),
                ('demail', models.EmailField(max_length=50)),
                ('dpassword', models.CharField(max_length=50)),
                ('dmobile_number', models.CharField(max_length=10)),
                ('dage', models.IntegerField(default=1)),
                ('dspecial', models.CharField(max_length=50)),
                ('dexperience', models.IntegerField(default=0)),
                ('dcountry', models.CharField(max_length=10)),
                ('dstate', models.CharField(max_length=10)),
                ('dcity', models.CharField(max_length=10)),
                ('dcreated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='select', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='select', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='select', max_length=10),
        ),
    ]
